# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "trusty" do |trusty|
    trusty.vm.box = "ubuntu/trusty64"
  end
  config.vm.define "trusty2" do |trusty|
    trusty.vm.box = "ubuntu/trusty64"
  end
end
