# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "trusty" do |trusty|
    trusty.vm.box = "ubuntu/trusty64"
  end
  config.vm.define "wily" do |wily|
    wily.vm.box = "ubuntu/wily64"
  end
end
